name: "Build Installers"

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  BuildLinuxInstaller:
    if: (github.repository == 'miabatta/deadline-cloud-for-blender')
    name: Build Linux Installer
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    tag: ${{inputs.tag}}
    oses: "['Linux']"
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_build_installers.yml@mainline
    secrets: inherit